[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "parserf"
version = "0.1.0"
description = "Library for parsing earthquake rupture forecast (ERF) datasets."
readme = "README.md"
requires-python = ">=3.12"
license = { text = "Apache-2.0" }
dependencies = [
  "geopandas",
  "matplotlib",
  "numpy",
  "pandas",
  "pyproj",
  "scipy",
  "shapely",
]

[project.optional-dependencies]
dev = [
  "pre-commit",
  "pytest",
  "pytest-cov",
  "ruff",
]
examples = [
  "jupyter",
]

[project.urls]
Repository = "https://github.com/asarmy/parserf"

[tool.setuptools]
include-package-data = true
package-dir = { "" = "src" }

[tool.setuptools.packages.find]
where = ["src"]

[tool.coverage.run]
relative_files = true

[tool.ruff]
line-length = 99
target-version = "py312"

[tool.ruff.lint]
select = ["E", "F", "I"]
