[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "u3mfd"
version = "0.1.0"
description = "Parser for UCERF3 fault model solutions and NSHMP seismic hazard data"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "geopandas",
    "matplotlib",
    "numpy>=2.4.0",
    "pandas",
    "pyarrow>=23.0.1",
    "pyproj",
    "scipy",
    "shapely>=2.1.2",
]

[project.optional-dependencies]
examples = [
    "ipykernel>=7.2.0",
    "jupyterlab",
]

[dependency-groups]
dev = [
    "black>=25.12.0",
    "pdoc>=16.0.0",
    "pre-commit>=4.5.1",
    "pytest>=9.0.2",
    "pytest-cov",
    "ruff>=0.14.10",
]

[tool.setuptools]
include-package-data = true
package-dir = { "" = "src" }

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["src"]

[tool.coverage.run]
relative_files = true

[tool.ruff]
line-length = 99
target-version = "py312"
exclude = ["scratch.py"]

[tool.ruff.lint]
select = ["E", "F", "I"]
